# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: minimal
day_night: false
font: native
font_size: L
logo: 'logo.jpg'

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: My research group description.
twitter: ''

# Contact (edit or remove options as required)

email: wangyi@dgut.edu.cn
phone: +86 0769-2286-2015
address:
  street: No.1 University Road
  # city: Dongguan
  # region: Songshan Lake
  city: Songshan Lake
  region: Dongguan, Guangdong, China
  postcode: '523808'
  country: China
  country_code: cn
coordinates:
  latitude: '22.90522222222'
  longitude: '113.8741'
directions: School of Cybersecurity, Building 9A, Level 3, Room 301
office_hours:
  - '09:00 ~ 17:00'
# appointment_url: 'https://calendly.com'
contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: false
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: false
  project: true
  publication: true
  talk: false
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: '© 2021 · Powered by wowchemy'
  # notice: '© 2021 · Powered by [wowchemy](https://wowchemy.com/zh/).'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: false
    docs: false
    project: false
    publication: true
    talk: false
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
